### PR TITLE
Decrease coverage calculation time

### PR DESCRIPTION
**Pull request by edwin7026**
This Pull request is related to issue mentioned in #27 
The PR involves the following feature additions:
- Parallelization of coverage computation. Number of processes to be spawned can be provided using `--procs` option in CLI. Default value is 1.
- Removal of hit coverpoints from working CGF dictionary. This feature can be enabled by using `--no-count` option in CLI. It is disabled by default.

### CODE REVIEW

**Comment by neelgala** [comment]
can you provide examples on how much reduction in time is achieved ?

**Comment by edwin7026** [comment]
> can you provide examples on how much reduction in time is achieved ?

I ran benchmarks: (Test cgf is rv64i.cgf and test suite is the one in riscv-archtest)
- With procs = 1 and no_count = False: 734 s
- With procs = 1 and no_count = True: 690 s
- With procs = 3 and no_count = False: 730 s
- With procs = 3 and no_count = True: 691 s

Inference:
Enabling `no_count` option shows good decrease in coverage calculation time. Parallelization reports inconsistency in the current workload as it is pretty small. It would be advantageous when CGF file size is large.

**Review by neelgala — APPROVED** [review]

**Comment by allenjbaum** [comment]
I'm not understanding.
With no_count = True ,    going from 1->3 procs slows down the amount of
tine by ~.15%
With no_count = False ,  going from 1->3 procs speeds up.  the amount of
tine by ~.50%
Why are either of those "good"? Shouldn't you be expecting a 2-300%
increase?

**Comment by pawks** [comment]
The improvements look nominal because of the nature of the inputs themselves. Once the size of cgfs increase(such as for the f extension) the speedup will scale. The support for fextensions wasn't available at the time.

**Pull request merged**
