### PR TITLE
Added register entries for pmpaddr registers

### PR DESCRIPTION
**Pull request by alitariq4589**
In this PR I have added pmpaddr registers without which riscv_isac cannot perform coverage of the coverpoints which include pmpaddrX registers. After this PR, the cgf files with pmp address registers (e.g. pmpaddr1) will successfully execute with `riscv_isac`

### CODE REVIEW

**Comment by neelgala** [comment]
@alitariq4589 maybe include the exhaustive list of pmpcfg* as well in this PR

**Comment by alitariq4589** [comment]
> @alitariq4589 maybe include the exhaustive list of pmpcfg* as well in this PR

Sure. I am adding it.

**Comment by alitariq4589** [comment]
@neelgala I have added all pmpcfg* registers

**Comment by pawks** [comment]
You'll also need to add them to the dictionary inside the `csr_registers` class. The class only contains values for 16 pmp entries right now.

**Comment by alitariq4589** [comment]
@pawks I dont see any pmpaddr* register in `csr_regs` dictionary. Are they also needed to be added ?

**Comment by pawks** [comment]
They are added [here](https://github.com/riscv-software-src/riscv-isac/blob/1952af2d3e5e5e705fb0466381512b7770e82734/riscv_isac/coverage.py#L571).

**Comment by allenjbaum** [comment]
Slightly off topic: The PMP spec has lot of corner cases, and has one very
ugly oversight: the number of PMP registers is not specified, nor is there
a specified allocation.
Maybe every other register? Only the prime numbered ones? Completely legal.
When tests are generated for BMP, it would be useful to define the CSRs
with #defined names instead of numbers, so that a test could be modified to
adjust for non-standard allocations just by changing the #defines base on a
mask of implemented CSRs provided by the model

**Comment by UmerShahidengr** [comment]
Good point @allenjbaum, but here we are trying to simplify the register entries by following Sail as reference. Currently Sail supports 16 pmpaddr and 4 pmpcfg regs so those entries have been added in ISAC to test some coverpoint definitions related to PMP.

**Comment by neelgala** [comment]
@alitariq4589 please change the target branch of the PR to `dev` and rebase to it. Also provide an entry in the CHANGELOG.md file under the `WIP-DEV` section.

**Review by neelgala — APPROVED** [review]

**Pull request merged**
